FROM ubuntu:20.04

LABEL "org.btestlab.licenses"="BSD-3-Clause"
LABEL "org.btestlab.title"="DNS forwarder and cache sever for localy hosted server."
LABEL "org.btestlab.vendor"="dnsmasq"

ARG gateway
ARG ip4
ARG upstream
