network:
  version: 2
  renderer: networkd

  ethernets:
    enp4s0:
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.1.60/24
      gateway4: 192.168.1.1
      nameservers:
        addresses: [192.168.1.1]

  wifis:
    wlp3s0:
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.1.30/24
      gateway4: 192.168.1.1
      nameservers:
        addresses: [192.168.1.1]
      access-points:
        "{wifi}":
          password: "{password}"
